name: Wiki Deployment

on:
    push:
      branches:
        - master

jobs:
  sync-wiki-files:
    name: Sync Wiki Files

    runs-on: ubuntu-latest

    steps:
      - name: Merge to .wiki
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: wiki
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_DEPLOYMENT_ACCESS_TOKEN }}
